### ISSUE TITLE
Sync components to mazer

### ISSUE THREAD

**Issue by fzn0x** [fzn0x/mazer-nuxt#101]
Mazer has lot new components and minor texts updates for this repository need to sync.

Will be released as v2 minors

**Comment by WailanTirajoh** [comment]
hi! im migrating dark themes component from mazer to mazer-nuxt at feat: add dark theme #293

**Comment by nimdeveloper** [comment]
I think it will be better to have a UI kit project for Mazer and use it in this project. I feel this is going to be messy a bit.

**Comment by nimdeveloper** [comment]
I will migrate `Forms & Tables` section
- [ ] Form elements
- [ ] Form layout
- [ ] Form validation
- [ ] Form editor
- [ ] Table
- [ ] Datatables

**Comment by fzn0x** [comment]
I'm not sure we really an UI Kit project to use, we can just add new components file and show it in [subitems ](https://github.com/fzn0x/mazer-nuxt/blob/main/store/data/sidebarItems.ts)

**Comment by nimdeveloper** [comment]
> I'm not sure we really need an UI Kit project to use, we can just add new components file and show it in [subitems ](https://github.com/fzn0x/mazer-nuxt/blob/main/store/data/sidebarItems.ts)

Yeap, that make sense.

**Comment by kiranraoboinapally** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
MDBYB, @gokopotter, @1Aviator1, @Rangena, @hoangthu90306, @SimonSaysSoWhat, @jameshoo7, @MuhtasimTanmoy, @BaheFagan, @pygmypossumchatting, @saitgn7, @ar4s-eth, @uqee, @fuyutarow, @jeenaprakash, @Dosthane08, @Tommie8193, @hyunjungyu, @iamdivisionbyzero, @Chandan933362

**Comment by cuichacha** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!amimaro, @JedWag, @FLAKEYCHALK, @0xdrew, @Hariram2001, @Brymes, @neha-nupoor, @GuyNameW, @0xViking, @samnang, @NickGoko, @devonartis, @udofia2, @WoL256, @shawnxbc, @3haratjk, @admrb21, @KenMan79, @youssefmohssine17, @anhfactor
